/*
 * This file is generated by jOOQ.
 */
package org.zwierzchowski.marcin.db;


import org.zwierzchowski.marcin.db.tables.Messages;
import org.zwierzchowski.marcin.db.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.messages</code>.
     */
    public static final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
