/*
 * This file is generated by jOOQ.
 */
package org.zwierzchowski.marcin.db.tables.records;


import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;
import org.zwierzchowski.marcin.db.tables.Messages;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessagesRecord extends TableRecordImpl<MessagesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.messages.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.messages.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.messages.content</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.messages.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.messages.sender</code>.
     */
    public void setSender(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.messages.sender</code>.
     */
    public String getSender() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.messages.date</code>.
     */
    public void setDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.messages.date</code>.
     */
    public LocalDateTime getDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.messages.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.messages.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessagesRecord
     */
    public MessagesRecord() {
        super(Messages.MESSAGES);
    }

    /**
     * Create a detached, initialised MessagesRecord
     */
    public MessagesRecord(Integer userId, String content, String sender, LocalDateTime date, String status) {
        super(Messages.MESSAGES);

        setUserId(userId);
        setContent(content);
        setSender(sender);
        setDate(date);
        setStatus(status);
        resetChangedOnNotNull();
    }
}
